Models/TreeModel.cpp

Ok, so I experimented with a couple of different styles for the tree. The top-left one is what the current master branch has, use a demibold font with groups that actually have child nodes. I preferred this over the old always-bold primary nodes in old GM. This pull request actually changes it to the top-right screen for a number of reasons.
* First, the bottom-right one was achieved by turning off the `Qt::ItemIsEnabled` flag, which makes the item unselectable. I tested and ensured that I can still show a context menu for the item this way, but it feels weird because you can't use F2 to select and rename the empty folder like the other folders.
* I feel the bottom-left one, using a folder icon with files for groups with child nodes, looks really trashy. Makes the whole tree look too …

Tree View/Empty Folder Presentation

---

Components/RecentFiles.cpp
Components/RecentFiles.h
Editors/BackgroundEditor.ui
MainWindow.cpp
MainWindow.h
MainWindow.ui
Plugins/ServerPlugin.cpp
RadialGM.pro
main.cpp

This adds the ability to load Classic GameMaker Files and GameMaker: Studio 2's YYP project format from the open dialog.
This follows from the work on https://github.com/enigma-dev/enigma-dev/pull/1179 to get GMK & YYP support in the CLI.
While I was doing this I used QSettings to remember the window state and add a recent files menu.

Window State, Classic GMK & YYP Support, and Recent Files

---

CmakeLists.txt
README.md
RadialGM.pro
appveyor.yml
main.cpp
qtplugins.cpp
resources.rc

This follows #27 using the instructions from #26 to build RGM on AppVeyor. We just download the Qt static build from `RadialGM-deps` and compile RadialGM and deploy it to the GitHub releases page.

Setup AppVeyor Build Using MSVC 2017 & Releases

---

appveyor.yml

The developers at AppVeyor already took care of our issue with vcpkg and their updated Visual Studio 2017 image. We can go back to using the latest one instead of the previous one now.
https://www.appveyor.com/updates/2018/09/01/
https://github.com/appveyor/ci/issues/2600

AppVeyor New VS 2017 Image

---

CmakeLists.txt
Components/RecentFiles.cpp
Editors/CodeEditor.cpp
Editors/CodeEditor.h
Editors/CodeEditor.ui
Editors/ScriptEditor.cpp
Editors/ScriptEditor.h
MainWindow.cpp
MainWindow.h
MainWindow.ui
Models/ImmediateMapper.cpp
Models/ImmediateMapper.h
Models/ProtoModel.cpp
RadialGM.pro
Widgets/CodeWidget.cpp
Widgets/CodeWidget.h
Widgets/CodeWidgetPlain.cpp
Widgets/CodeWidgetScintilla.cpp
images.qrc
main.cpp
qtplugins.cpp

Attempting to cleanup and organize how we want the editors that are for code to be implemented. RGM can still be built in two modes, one that uses QScintilla, and one that uses QPlainTextEdit.
* CodeWidget.h declares the interface for a code editing widget
* CodeWidget.cpp defines an implementation of code widget common to all other implementations
* CodeWidgetPlain.cpp defines an implementation of code widget using QPlainTextEdit
* CodeWidgetScintilla.cpp defines an implementation of code widget using QScintilla
* Changed the CMake lists and qmake pro file to link print support, but it doesn't work for some reason in the AppVeyor build
* Uses widget promotion to add the code widget to the code editor, which script editor derives from
* Now serializes with the main window settings whether …

Chinchilla Functionality

---

CmakeLists.txt
Editors/RoomEditor.ui
RadialGM.pro
Widgets/ColorPicker.cpp
Widgets/ColorPicker.h

Well, yeah, we need one of these so here it is. I obviously used a `Q_PROPERTY` to implement the user property of the widget so that it can be mapped to models with a widget mapper. It handles transparency just fine using the transparency pattern and drawing a filled rectangle with the color on top of that. Went ahead and promoted the one in the room editor to it.

Basic Color Picking Widget

---

CmakeLists.txt
Editors/BackgroundEditor.cpp
Editors/BackgroundEditor.ui
Editors/BaseEditor.h
Editors/SettingsEditor.cpp
Editors/SettingsEditor.h
Editors/SettingsEditor.ui
Editors/SpriteEditor.ui
MainWindow.cpp
MainWindow.h
MainWindow.ui
Models/TreeModel.cpp
Models/TreeModel.h
Plugins/RGMPlugin.h
Plugins/ServerPlugin.cpp
Plugins/ServerPlugin.h
RadialGM.pro
Widgets/BackgroundRenderer.cpp
Widgets/CodeWidget.h
Widgets/CodeWidgetPlain.cpp
Widgets/CodeWidgetScintilla.cpp

There are two main goals of this pull request. I was hoping to mock up a nice way of selecting configurations and targets and make compiling work. Additionally I wanted to get completions working for the script editor.
Summary of Changes
----
* Added `SettingsEditor` designer form class with the basic ENIGMA settings for compiling.
* Added 4 new icons to use in the script editor's autocompletion window. One of them is an f(x) icon for functions and the other three are colored right-facing arrows for constants/variables/globals. Resources will later just use their resource icons when we add that.
* Added a system cache to the main window for plugins to communicate available systems to the built in editors. This is primarily just used by the settings editor so it can populate the API combos …

GRPC & Compiler Related Features

---

Models/ProtoModel.cpp

This fix here stops the IDE from converting unknown resources to sprites with an id of 0 which results in the id collision in #41.
I dug out the real cause of the regression. The `ResourceModelMap` that fundies created causes the type case of the help node to change from 0 (not set/unknown) to 2 (sprite) when it constructs a recursive map of the project model.
It causes this by allocating a message and then constructing a `ProtoModel` for the submessage of every tree node. The problem occurs because the tree node resource is a oneof field. Fundies does check that the field is a oneof and `HasOneof` but he was still calling `MutableMessage` even in the case that the oneof field was not actually set. `MutableMessage` will allocate and set the oneof field, regardless of whether it was …

Fix for Unknown Resource Conversion to Sprites

---

Models/TreeModel.cpp

This fixes the actual crash in #41 and needs to be done regardless. Primarily, sprites with no subimages should not crash the IDE.
Currently, the change here behaves differently than GM and LGM. By returning an invalid `QVariant` when the sprite/object/background icon can not be obtained (e.g, sprite with no subimages) this essentially means we return no icon. The label of the tree item is then shifted left with no placement for the icon. This is not the same as returning an empty/translucent icon of a fixed size like GM always did and continues to do in GMS2.
However, I feel that having the empty icon could be confusing, because it looks as if the resource just has an empty icon, which is not quite the same (e.g, an object that doesn't have a sprite). But anyway, I can certainly change …

Fix Tree Model Crashes for Missing Previews

---

MainWindow.cpp

This was a minor logic mistake that I made. I used the subscript operator `[]` to check if a subwindow was already added for a given tree node. This was not what I actually intended, because the subscript operator will insert the item if it's not present. The other place that the subscript operator is still used was intentional.
1) Attempt to open an unknown resource by double clicking, like the help/info node
2) Select the help/info tree node with a single left click and then press F2 to rename it
3) After renaming the item the crash occurs
This basically fixes a crash that occurs when trying to open unknown resources (those with type case not set). One such resource at the moment in the help node I've been addressing in other ways. Regardless of whether we want to keep help/info as a …

Fix Crash When Opening Unknown Resources

---

Models/TreeModel.cpp

This fixes a crash that can be reproduced by creating a room and then an object. The logic mistake I made was in `TreeModel::addNode` where the child size is one larger than the index of the row I want to insert into the tree. The reason is because the child is already added to the parent by way of `TreeNode::add_child` which is called in `MainWindow::CreateResource` before `addNode` is even called.
I will need to be extra careful when I do the tree drag and drop.

Add Tree Node Crash Fix

---

Plugins/ServerPlugin.cpp
Widgets/CodeWidgetScintilla.cpp

I have already noticed and people have already mentioned the latest RGM crashes a few seconds after open if emake is not found. This is because the ResourceReader has its `finished()` called without its `started()` ever being called in the case that emake is not found. The `CodeWidget::finalizeKeywords` is where the crash occurs because `CodeWidget::prepareKeywordStore` was not called to allocate and prepare `sciApis` to be used.
This change fixes the crash by making all of the keyword API just be a noop if `sciApis` wasn't allocated. I've also additionally added another directory where emake can be found, an `enigma-dev` folder directly next to the RGM executable.

Missing emake Crash Fix

---

MainWindow.cpp
MainWindow.ui
Models/ResourceModelMap.cpp
Models/ResourceModelMap.h
Models/TreeModel.cpp
Models/TreeModel.h

Alright, I wanted to tackle the drag and drop for the tree because I knew it was going to be a little painful. I am very happy with the results here. As of now, it's pointer based and doesn't handle any IPC-based dragging and dropping of nodes, but does properly support extended selection, drag, and copy within the same RadialGM process now.
* Changed `TreeModel` constructor to accept `ResourceModelMap` so the tree model is capable of adding new resources to the map when doing a drag copy operation.
* Changed `MainWindow::CreateResource` to allocate a new `TreeNode` directly instead of through the root. I did this originally anticipating that `TreeModel::addNode` would be used by the drag and drop code, but ultimately it wasn't.
* Changed TreeModel::addNode to append the allocated child …

Tree Drag & Drop

---

.gitignore

Lots of problems today with helping daz and Bloodseeker build for Windows and Linux respectively. Some of the problems were caused by the submodule falling behind and losing fixes Josh made to prevent `JavaStruct.h` pollution into the protos. Also with the newer Qt Creator, it decided to give me some `*.stackdump` file we obviously don't want to be committing, so I've added that to ignore.

Update ENIGMA Submodule

---

CMakeLists.txt

I'm getting errors when trying to use the static RGM release in my enigma-dev setup that has emake built with the server. It seems to be rejecting localhost connection.
```
$ ./RadialGM-Win32-Release-x64.exe
E0505 15:38:43.277000000  6244 resolver_registry.cc:80] don't know how to resolve 'localhost:37818' or 'dns:///localhost:37818'
E0505 15:38:43.277000000  6244 resolver_registry.cc:80] don't know how to resolve 'dns:///localhost:37818' or 'dns:///dns:///localhost:37818'
E0505 15:38:43.277000000  6244 channel.cc:99] channel stack builder failed: {"created":"@1557085123.277000000","description":"resolver creation failed","file":"C:\Tools\vcpkg\buildtrees\grpc\src\v1.19.1-81627204c3\src\core\ext\filters\client_channel\request_routing.cc","file_line":546}
```
I read that this may be caused …

Fix Release Build

---

Models/SpriteModel.cpp

When creating a new sprite, it still tries to get the sprite data. index.row() returns -1 in this case, and then attempting to get a protobuf on that index causes a SIGSEGV.

Fix crash when creating a new sprite

---

Editors/BaseEditor.h
Models/ResourceModelMap.cpp
Models/TreeModel.cpp

This is a very simple set of changes for plionz that should make the tree model a bit more efficient. 
Basically the idea is to move the rows for non-copy drag and drop, rather than remove them and reinsert them. This actually will correct any persistent model indexes obtained from the tree model since Qt internally updates their references automatically for us.
While I was in here I fixed crashes involved in drag-copy of tree groups too. In addition to fixing the underlying crash, me and polygonz decided on skipping the drag-copy of tree groups until `duplicateNode` is made recursive or we see a need to implement this functionality since GM's UI never supported it.

Tree Model Drag & Drop Fixes

---

Models/TreeModel.cpp

Minor regression fix stemming from #67 for polygonz again. I just needed to change up the logic a little more so that we don't offset the rows unless we actually move the row. We also need to respect whether Qt tells us we can actually move the row.

Tree Move Fixes

---

RadialGM.pro.shared

This is to make that warning go away when opening the project in the latest Qt Creator. It occurs because the `FileVersion` is different in the shared settings from the one in the user settings Qt Creator generates.
https://doc.qt.io/qtcreator/creator-sharing-project-settings.html
It's ok for us to do this as it will still work for people with older Qt Creator versions. They will get the same warning. This just means that people with the latest Qt Creator don't have to deal with the warning. So, in general, it's ok for us to regularly update this `FileVersion` to avoid the warning. I tested to confirm by setting the FileVersion older like it was, and setting it newer than my installed Qt Creator.

Update Shared Settings File Version

---

MainWindow.cpp

This fixes a regression I introduced in #63 by accidentally deleting the call to read the main window's settings. Polygonz caught it by mentioning that the maximized state of the window and its geometry was not persisting between sessions. I have inserted the call after the setup of the editor diagnostics, which is what I think caused me to accidentally remove it, that way if there are problems reading certain settings they can be logged to the editor diagnostics.

Fix Main Window Settings Regression

---

main.cpp

Splitting this out from polygonz changes so I can talk about it. With my 2k monitor, I am not seeing any difference with or without the setting applied, but polygonz claims to and Rusky backs him stating the screenshots which showed it fixing the problem for polygonz.
For now, I just want to allow polygonz to enable the setting permanently and see no need for a preference yet. Later, if somebody has an issue, we can look at adding a three-button radio group or two checkboxes. One will force the high DPI to be enabled, and one will force it to be disabled, since there are Qt settings for both. I see no need for the preference because Rusky has told me the Windows Compatibility DPI override should override it if the user really needs to disable DPI for some reason.
What confuses me is that …

High DPI Fixes

---

main.cpp

This corrects a mistake I made in #73 which caused the high DPI fix to not actually work. Apparently it must be set statically before the QApplication construction.

High DPI Fix Fix

---

Components/ArtManager.cpp

Ok, so I learned a hard lesson today. For a few months I have been confusing temporaries with locals. It is _never_ ok to return a reference to a local variable! Constant qualification only extends the lifetime of _temporary_ objects, not local variables. Simple solution here was to just make the invalid pixmap returned by cached pixmap a static local. This seems to fix crashes for me in the room editor when there are objects with no sprite.

Cached Pixmap Crash Fix

---

MainWindow.cpp

Because I combined the condition of whether the action exists with whether it's not checked, I had it erroneously reporting that the toggle button didn't exist sometimes. The simple and correct solution was to just move the condition for whether the action is checked inside the outer condition for whether the action exists or not.

Fix Toggle Diagnostics Action Check

---

RadialGM.pro

Remember that fundies did not like how the CLI server option was called disabled and so he had it changed to enabled? Well, keeping in that tradition, I am inverting the RGM option for enabling scintilla. Now it's enable instead of disable (still disabled by default in the pro). This just means all of the options we provide across projects are semantically consistent.

RGM Enable Syntax Highlight

---

CMakeLists.txt
MainWindow.cpp
Plugins/ServerPlugin.cpp
RadialGM.pro

This is just the start of my GRPC fixes that I've been discussing. First, I am enabling the server plugin again. Then I fixed the file search pattern to whitelist "emake" and "emake.exe" so that "emake-tests.exe" is no longer matched. I went with this for now because I see Qt only accepts globs, not actual regexes, so the regex Josh gave me won't work yet. Next, I changed the timer delay to 1ms to prevent the plugin from hogging 100% of a CPU core. Finally, I added `rgm_enable_grpc_server` config option (disabled by default) in both the pro file and the CMakeLists to make it easier to turn the GRPC server on and off, and so I can keep working on it without undoing fundies commenting out my code.

Restore GRPC

---

CMakeLists.txt

Enable GRPC client for the Azure build on Win32.
https://cmake.org/cmake/help/latest/module/CMakeDependentOption.html#module:CMakeDependentOption
Also fix the option itself by removing PARENT_SCOPE, which was actually setting the variable a scope above the current scope and thus causing it to not actually build the server plugin.
https://cmake.org/cmake/help/v3.3/command/set.html
I tested the artifact produced from this build and it does indeed have the GRPC client built in. However, when launched from MSYS2 it doesn't seem to launch emake like my local build does. Although, if emake is manually launched, the Azure artifact will still communicate with it.
That just means this pull request is correct and we just need to work out yet how we expect people to launch this thing.

Azure Enable GRPC for Win32

---

CMakeLists.txt

It's `qscintilla2_qt5.dll` for me in MinGW64 and thus Azure so I added that plus a bunch of other possibilities from a find qscintilla CMakeLists I found online. Then it was able to find the dll, link it, and fundies installer copied it.
I had to remove `CodeWidgetPlain.cpp` from the sources list because fundies forgot to when he added the find library for qscintilla2 condition. Once I made it find the dll, we were getting multiple definition errors from linking both code widgets until I did this.
Finally, I had to investigate why line numbers were not working and the editor diagnostics was reporting "signal not found in QsciScintilla" in the log window. It turns out that `-DQSCINTILLA_DLL` is what happens when you `CONFIG += qscintilla2` in the qmake pro. That definition is needed to …

Fix QScintilla2 CMake Issues

---

Plugins/ServerPlugin.cpp
Plugins/ServerPlugin.h

The basic idea with this pull request is to allow us to actually process multiple RPCs at once. Although I had already switched us to the async API, we were not actually async before!
I was using the state of each call's state machine as the tag, which made it impossible to identify which call was receiving an event. So the idea I had here was to use the pointer of the call as the tag so our main loop knows which call to process the event for.
https://grpc.github.io/grpc/cpp/classgrpc__impl_1_1_client_async_reader.html#a97a711a7b063bd053c7f9f9eb43e927e
To do this without breaking the state machine, I had to have the state machine initiate its state transition before making any of the calls. In example, you'll see that start immediately sets the state to connect before starting the call …

Simultaneous RPCs

---

Models/TreeModel.cpp

This is my attempt to work around #96 since Qt closed my bug report. I wrap the disabled folder pixmap in a QIcon, which does scaling, so that this model returns nothing but QIcons. The alternative would be to change all of the uses of QIcon to QPixmap, and return only pixmaps, but pixmaps are not scaled automatically. The other alternative is we write our own tree view delegate that actually fixes the Qt bug report I filed.
To me this seems like a fine work around, I'm just bothered by the tree having icons smaller than toolbars and other UI elements.
| Before                                                                                                                         | After …

Tree Folder DPI Fix

---

Components/Logger.h
Models/MessageModel.cpp
Models/MessageModel.h
Models/RepeatedMessageModel.cpp
Widgets/PathView.cpp
Widgets/RoomView.cpp

This is how Josh would like to resolve #122 by making it explicit when you are ok accepting the default value from the model. I had to also allow column 0 as a special sentinel for `RepeatedMessageModel` to return a pointer to the requested model so that I have an actual way to call `dataOrDefault` on repeated messages. The hack avoids the complication of having to add `dataOrDefault` on all the higher level models and interfaces, such as the sort filter proxy model.

Default Model Values

---

MainWindow.cpp

I just noticed this was different from LGM so I decided to tweak it. Interestingly, all versions of GM before GMSv1.4 did not even have this menu. Even when GMSv1.4 finally added it, they didn't use the MDI subwindow icons like LGM did. Obviously the icons help to easily pick out the windows from the list. Later I would like sprites/backgrounds/objects to actually use the same icon as the tree node too.
| Master | Pull |
|--------|------|
|![Master MDI Window Checkboxes](https://user-images.githubusercontent.com/3212801/88857994-484d2800-d1c5-11ea-958f-d0713f9c5044.png)|![Pull Request MDI Icons](https://user-images.githubusercontent.com/3212801/88857968-3bc8cf80-d1c5-11ea-9405-5a5dec682c07.png)|

Window Menu MDI Icons

---

Editors/ScriptEditor.cpp
Editors/ShaderEditor.cpp

The reason these two didn't have their own window icons already is because they are reusing the same `CodeEditor.ui` form, which is totally acceptable. The alternative would be for us to create separate `ShaderEditor.ui` and `ScriptEditor.ui` forms that both embed the `CodeEditor.ui` like it's a custom widget. I have no particular preference myself.
I should mention that this relates to #137 keybinding preferences. In GMS2 the keybinding preferences are the same for the script and shader editors, likely because YoYo is doing a similar kind of abstraction internally for the editor they built.
https://docs2.yoyogames.com/source/_build/1_overview/2_quick_start/8_shortcuts.html

Script/Shader Editor Window Icon

---

Editors/BaseEditor.cpp
Editors/BaseEditor.h
Editors/PathEditor.cpp
MainWindow.cpp
MainWindow.h
Widgets/AssetScrollAreaBackground.cpp
Widgets/AssetScrollAreaBackground.h

This was quite a bit of a mess and actually inconsistent with both how GUI frameworks are designed and GM8.1 path editor.
* Removed FocusGained/FocusLost/HasFocus from the BaseEditor.
* Every QWidget has a Qt provided `hasFocus()` which the framework automatically handles for us including the focus traversal order. It's extremely rare that you should ever be doing your own custom focus handling in any framework really.
https://doc.qt.io/qt-5/qwidget.html#focus-prop
https://doc.qt.io/qt-5/focus.html
* Removed the `MainWindow::MDIWindowChanged` slot which was handling the custom focus we no longer need.
* Removed the custom `_parentHasFocus` member and its setter from the asset scroll area background.
* Switched A and D to left/right respectively in the asset scroll area background because …

Cleanup Focus Handling

---

MainWindow.cpp

Just changing up the delete resources confirmation dialog a bit. I hide the list of resources in the details section. Even if we decide not to use the details section we should use [informative text](https://doc.qt.io/qt-5/qmessagebox.html#informativeText-prop) instead of string interpolation since the platform handles that for us.
| Master                                                                                                                          | Pull                                                                                                                             |
|---------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------ …

Delete Confirmation Details

---

Editors/BackgroundEditor.cpp
Editors/BackgroundEditor.ui

Bringing some of my layout improvements from #144 over to master as their own changes.
* Changes properties layout from vbox to form so it has two columns where that's needed like the name field.
* Adds the name label and a buddy field.
* Maps the name field to the tree node.
* Changes the tileset groupbox to fixed vertical size policy.
| Master                                                                                                                                             | Pull                                                                                                                                                     |
|----------------------------------------------------------------------------------------------------------------------------------------------------|----- …

Background Editor Layout Improvements

---

Editors/SpriteEditor.cpp
Editors/SpriteEditor.ui

Same as #156 but for the sprite editor.
* Changes properties layout from vbox to form so it has two columns where that's needed like the name field.
* Adds the name label and a buddy field.
* Maps the name field to the tree node.
* Stretches the x/y origin line edits in the parent grid layout.
* Gives the root widget layout a proper "mainLayout" name.
* Gives the origin group layout a proper "originLayout" name.
* Gives the collision shape group layout a proper "collisionShapeLayout" name.
* Gives the BBox group layout a proper "bboxLayout" name.
* Gives all the labels in the BBox dimensions grid the correct buddy.
* Removes the bottom spacer in the properties layout that was used to push everything to the top since form layout does that automatically.
| Master …

Sprite Editor Layout Improvements

---

Widgets/CodeWidgetPlain.cpp

I guess fundies doesn't like word wrapping and he's not using the Scintilla code widget, so I decided to turn off word wrapping (the default for QPlainTextEdit) in our plain code widget until #160 is completed and it can be based on the preference. This way at least our Scintilla and Plain code widgets are consistent with each other until such time. Although, due to yet another MSYS2 package issue I am not able to build our QScintilla based code widget now because I am missing the debug library.
For reference, QScintilla does no wrapping by default.
>The default is that lines are not wrapped.
https://www.riverbankcomputing.com/static/Docs/QScintilla/classQsciScintilla.html#ac04428d2f90c36458d68a673f107e40c
QPlainTextEdit does wrap by default.
>By default, this property is set to …

Disable Plain Code Widget Word Wrapping

---

MainWindow.cpp
Models/MessageModel.cpp
Models/ProtoModel.cpp

First, the `Qt::ItemFlags` constructor for int was deprecated, so neither `0` nor `nullptr` were correct for invalid model indexes. The correct replacement is `Qt::NoItemFlags` that is assigned `0` in the enum. Second, apparently I made a mistake when I added the simple about dialog using `QMessageBox` in that I was passing `0` for the window flags parameter, then later changed it to `nullptr` because I confused it with the parent parameter. That's not good because it needed the `Qt::Dialog` flag it gets by default, so I just removed that argument from the call.
https://doc.qt.io/qt-5/qmessagebox.html#QMessageBox-1

Fix Flag Warnings

---

Editors/PathEditor.cpp

This changes the vertical header resize mode so the rows are only as tall as they need to be to fit the display value. It looks neater and allows more points to be displayed. I could not get the speed column to show because it requires #127 to be solved. There are only 3 columns, and the first one is a junk column which we are hiding. I was not able to right align the cell display values like I wanted either and it requires a similar solution, because we will either need to handle `Qt::TextAlignmentRole` in the model, create a proxy model, or use a custom style delegate on the table.
| Pull                                                                                                                     | Master …

Path Editor Points List Row Heights

---

CMakeLists.txt
Editors/IncludeEditor.cpp
Editors/IncludeEditor.h
Editors/IncludeEditor.ui
RadialGM.pro

This adds an editor for included files like the one I added to LateralGM which I based off of GameMaker 5's data file editor.
* We still need an include proto, so I haven't added any actual functionality and you can't open the editor yet.
* I decided to continue with the file name being separate, like GM5 and _unlike_ GMS, so we don't have file extensions in the tree.
* I've clearly kept several options that GMSv1.4 deprecated which I am not sure if are still useful.
* I've not included the target options that GMSv1.4 introduced because I don't know how we plan to handle that yet.
| RGM | LGM | GM5 | GMSv1.4 |
|-----|-----|-----|---------|
|![RGM Include Editor](https://user-images.githubusercontent.com/3212801/91336536-0ef5e100-e7a0-11ea-9103-f5a79c02f564.png)|![LGM Include …

Included File Editor

---

Editors/SpriteEditor.cpp

This fixes the show checkboxes on the sprite form so you can click the label to toggle the checkbox. I removed the second label and added the text directly to the checkbox. Then I used `setLayoutDirection` to put the label to the left of the checkbox like fundies had it. This does not affect the text layout direction according to the documentation so it should not interfere with i18n here.
https://doc.qt.io/qt-5/qwidget.html#layoutDirection-prop

Sprite Show CheckBox Labels

---

Models/MessageModel.cpp

Apparently it's an assertion in protobuf to call `HasField` on a repeated field. This isn't actually reproducible anywhere yet, I just ran onto it in #173 when putting the layers into a list view because they have a repeated field column that I will probably end up hiding. Maybe later we can actually handle repeated fields correctly, but for now it's definitely not correct to check `HasField` since it crashes.

Fix Has Repeated Field Assertion

---

Models/ProtoModel.cpp
Models/RepeatedModel.h

Small fix to f2f3ba70d7aa4b18635747dd47f93f109c8623d8 that makes the explicit header data override anything the base models return, such as the field names. This allows me to translate or hide the field names in the column headers. None of the models now return the base implementation which is just the section number converted to a string, because I check if the base ProtoModel class returned valid header data.
Now I can do the following.

Proto Model Header Data Overriding

---

Editors/PathEditor.cpp
Editors/PathEditor.ui
Models/RepeatedModel.h

* Overload `RowRemovalOperation::RemoveRows` to accept a `QModelIndexList` of all selected rows.
* Set [QAbstractItemView::ExtendedSelection](https://doc.qt.io/qt-5/qabstractitemview.html#SelectionMode-enum) on Path editor points list view so we can select to delete many points at once. This does not change the fact that there is a current index inside the selection which has the focus if an edit is requested.
* Set [QAbstractItemView::SelectRows](https://doc.qt.io/qt-5/qabstractitemview.html#SelectionBehavior-enum) on Path editors points list view so we are actually selecting the entire point, which is similar to GM/LGM and feels less awkward. There is still a current index inside the selected row which has the focus if an edit is requested in a specific column item (aka the field).
* …

Extended Selection & Deletion of Path Points

---

Models/RepeatedModel.h

I made a mistake in #153 when I decided to change the header data to explicitly return an invalid QModelIndex, rather than the invalid data from the base class. I meant to return an invalid QVariant, which is what our other data implementations and official Qt models do. This caused a regression where none of the headers in any of our views are currently showing.

Header Data Oopsie

---

Models/RepeatedMessageModel.cpp
Models/RepeatedMessageModel.h

I figured out why the view editing isn't working, the repeated message model isn't forwarding the flags request to the submodels. This seems to work the way I expect. I can now edit the x/y columns of the path editor points list. I am also able in #173 to edit the layer columns.

Repeated Submodel Flags

---

Models/MessageModel.cpp

I went and added checkboxes for all the bools in all of the models. You can still set bools using the regular `Qt::EditRole` in addition to setting them using the `Qt::CheckStateRole` now. The fields of bool type will only return data for the `Qt::CheckStateRole` now. Every other field type will return an invalid QVariant for the `Qt::CheckStateRole`. Items will have the `Qt::ItemIsUserCheckable` flag if they return a valid QVariant for the `Qt::CheckStateRole` otherwise they will have the regular `Qt::ItemIsEditable` flag. I am using this right now in the room editing to check the visibility and such.

Boolean Model Checkboxes

---

Widgets/AssetScrollAreaBackground.cpp
Widgets/AssetScrollAreaBackground.h

Simpler part of #184 that only has the mapping point to asset abstraction. There will likely be other places we will need to map a point into the asset area other than mouse events. Maybe later we should just cache a QTransform for the asset scroll area too and do it that way to avoid all of these manual transformation calculations.

Abstract Map To Asset

---

Editors/PathEditor.cpp

This uses the header data override of #175 to translate the path point list column headers.
|Master|Pull|
|----|----|
|![Path Point Columns Master](https://user-images.githubusercontent.com/3212801/92177575-c62cd080-ee0e-11ea-92c2-aeede1e12e8e.png)|![Path Point Columns Pull](https://user-images.githubusercontent.com/3212801/92177519-a7c6d500-ee0e-11ea-9a7a-c53e9d07368c.png)|

Path Point Fields Translation

---

Models/TreeModel.cpp
Models/TreeModel.h

These should enable moving resources on disk in response to moving that resource in the tree.
We may need to revisit the TreeModel to make it use a custom wrapper of the TreeNode proto. This would save us some headache keeping track of the tree structure, and also where the files live on disk, when they were last saved, etc.

Add TreeModel::MakeResourcePath and ResourceMoved.

---

Editors/FontEditor.cpp

We can't set the preview font on the preview text area _before_ we've mapped the property widgets to the model. We have to grab the values out of the model to build a QFont, which is easier to grab from the mapped and loaded widgets. We also need to set the initial font on the range preview too. The previews now have the correct font the first time the editor is opened.

Font Preview Initialize

---

Editors/BackgroundEditor.ui

@JoshDreamland in #157 did not want me to right align the sprite bbox labels, so I am proposing to change the background frame's to be left aligned for consistency. I've done some more research and I think I can now articulate why Josh is correct in our specific case.
Yes it's true that the [Gestalt principles of grouping](https://en.wikipedia.org/wiki/Principles_of_grouping#Proximity) are why [right-aligned labels are easier to scan](https://uxmovement.com/forms/form-label-proximity-right-aligned-is-easier-to-scan/) when you are filling out a _sequential_ web form from top to bottom. However, left-aligned labels do work better where the user is scanning for just one field by name which they already know in advance. The latter is what we have in ENIGMA's case, as these fields are not …

Tileset Label Alignment

---

Editors/SpriteEditor.cpp
Editors/SpriteEditor.ui

I am iterating on our earlier change of the sprite collision mask radio buttons to combo boxes. It seems [GMS2 has gone the same direction](https://docs2.yoyogames.com/source/_build/2_interface/1_editors/sprites.html) but additionally combined the shape and bbox mode under the same group, which I am proposing here. I fixed a typo with the mapping to the shape combo box which was mapping the group before. I also decided to add the missing alpha tolerance slider while I was in here which will later need added to the automatic bbox computation.
| GMS2 | Pull | Master |
|------|------|--------|
|![GMS2 Collision Mask Properties](https://user-images.githubusercontent.com/3212801/103386041-f63d6500-4aca-11eb-9c6f-bad54d20b169.png)|![Pull Request Collision Mask …

Sprite Collision Mask Tweak

---

MainWindow.cpp

Possibly an unorthodox change, but I usually see packaged applications that install into the system store their libraries in /usr/lib/<thing> and /opt/<thing> so I added those accordingly.

Add static enigma-dev paths for linux to the paths RGM looks for enigma in
